synthetic_template/webUI/syndataUI/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.base, name='base'),
    url(r'^syntheticbox/', include('syntheticbox.urls')),
    url(r'^admin/', admin.site.urls),

]
if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

synthetic_template/webUI/syntheticbox/urls.py
from django.conf.urls import url

from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns 

app_name = 'syntheticbox'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^proc_data_dash/$', views.proc_data_dash, name='proc_data_dash'),
    url(r'^proc_json_processing/$', views.proc_json_processing, name='proc_json_processing'),
    url(r'^res_json_processing_plot/$', views.res_json_processing_plot, name='res_json_processing_plot'),
    url(r'^res_json_processing/$', views.res_json_processing, name='res_json_processing'),
    url(r'^res_json_processing_after/$', views.res_json_processing_after, name='res_json_processing_after'),
]

urlpatterns += staticfiles_urlpatterns()

synthetic_template/webUI/syntheticbox/models.py
import json
import numpy as np
import pandas as pd

def save_uploaded_file(f, current_file):
    with open(current_file + ".csv", 'wb+') as destination:
        for chunk in f.chunks():
            destination.write(chunk)

def chart_position_score(current_file):
    data = pd.read_csv(current_file)
    return_data = {'datapoint': [], 'top10': [], 'overall': []}
    score_value = data["Score"].tolist()
    position_value = [x for x in range(1, len(data) + 1)]
    for i in range(len(score_value)):
        return_data['datapoint'].append([position_value[i], score_value[i]])
    # get the median data
    attr_list = []
    for i in range(2, data.shape[1] - 1):
        attr_list.append(data.iloc[:, i].tolist())
    #####################
    colname = data.columns[2:5]
    topTen = 10
    for i in range(len(attr_list)):
        return_data['top10'].append(
            [colname[i], max(attr_list[i][0:topTen]), np.median(attr_list[i][0:topTen]), min(attr_list[i][0:topTen])])
        return_data['overall'].append([colname[i], max(attr_list[i]), np.median(attr_list[i]), min(attr_list[i])])
    return return_data

def save_file_to_server(file_name, data, ext='.txt'):
    with open(file_name + ext, 'w') as outfile:
        outfile.write(str(data))
    outfile.close()

def get_json_from_file(file_name):
    with open(file_name, 'r') as myfile:
        json_data = myfile.read().replace('\n', '')
    return json_data

def getSizeOfDataset(current_file):
    data = pd.read_csv(current_file+".csv")
    return len(data)

class DataAnalyzerUI(object):
    def __init__(self, threshold_size=100):
        self.threshold_size = threshold_size
        self.dataset_description = {}
        self.input_dataset = None
        self.display_dataset = None
        self.json_data = {}

    def read_dataset_from_csv(self, file_name=None, file_name2=None, join_column=None, join_type=None):
        file_name = file_name + ".csv"
        file_name2 = file_name2 + ".csv"
        try:
            df1 = pd.read_csv(file_name)
            df2 = pd.read_csv(file_name2)
            # join two DataFrame together
            df = df1.merge(df2, how=join_type, on=join_column)
            
            self.input_dataset = df
        except (UnicodeDecodeError, NameError):
            self.input_dataset = pd.read_csv(file_name, encoding='latin1')

        num_tuples, num_attributes = self.input_dataset.shape
        if num_tuples > self.threshold_size:
            self.display_dataset = self.input_dataset.head(self.threshold_size)
        else:
            self.display_dataset = self.input_dataset

    def get_dataset_meta_info(self):
        num_tuples, num_attributes = self.input_dataset.shape
        attribute_list = self.input_dataset.columns.tolist()

        meta_info = {"num_tuples": num_tuples, "num_attributes": num_attributes, "attribute_list": attribute_list}
        self.dataset_description['meta'] = meta_info

    def get_json_data(self):
        self.json_data = self.display_dataset.to_json(orient='records')

    def save_dataset_description_to_file(self, file_name):
        with open(file_name, 'w') as outfile:
            json.dump(self.dataset_description, outfile, indent=4)

    def save_dataset_to_file(self, file_name):
        with open(file_name, 'w') as outfile:
            outfile.write(str(self.json_data))

    def display_dataset_description(self):
        print(json.dumps(self.dataset_description, indent=4))

synthetic_template/webUI/syntheticbox/views.py
import json
import pandas as pd

from time import time, sleep

from django.urls import reverse
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render

import syntheticbox.lib.SyntheticWrapper as wrapper

from .models import DataAnalyzerUI
from .models import save_uploaded_file
from .models import getSizeOfDataset

def index(request):
    #play_data_list = ["adult_reduced","adult_with_missing_values","compas_reduced","customer_churn","risk_score"]
    play_data_list = ["customer_churn","risk_score","stockholm"]
    context = {"passed_play_data": play_data_list}
    # NOTICE: no .csv suffix in current passed file name
    #server_data_names_map = {"adult_reduced": "AR", "adult_with_missing_values": "AM", "compas_reduced": "CR", "customer_churn": "CC","risk_score": "RS"}
    server_data_names_map = {"customer_churn": "CC","risk_score": "RS","stockholm":"SH"}
    # create a time stamp for current uploading
    data_server_path = "./media/"
    play_data_server_path = "./playdata/syntheticbox/"
    cur_time_stamp = str(int(time()*1e7))
    upload_data_size_threshold = 20
    if request.POST:
        if request.FILES:
            # get user upload file
            upload_csvfile = request.FILES['user_upload_data']
            upload_csvfile2 = request.FILES['user_upload_data2']
            join_column = request.POST.get('user_join_column')
            join_type = request.POST.get('user_join_type')
            current_data_name = data_server_path + cur_time_stamp
            current_data_name2 = current_data_name + '2'
            save_uploaded_file(upload_csvfile, current_data_name)
            save_uploaded_file(upload_csvfile2, current_data_name2)
            # get the size of uploaded data
            upload_data_size = getSizeOfDataset(current_data_name)
            context_size = {"passed_play_data": play_data_list, "passed_size_flag":"false"}
            # if upload data size less than the threshold, back to upload page and alert user
            if upload_data_size <= upload_data_size_threshold:
                return render(request, "syntheticbox/index.html", context_size)
            request.session['passed_data_name'] = current_data_name
            request.session['passed_data_name2'] = current_data_name2
            request.session['passed_join_column'] = join_column
            request.session['passed_join_type'] = join_type
        else:
            selected_data = request.POST["dataset_select"]
            # create a copy of current play data set on server to allow differentiate multiple users at the same time
            cur_data = pd.read_csv(play_data_server_path + selected_data + ".csv")
            new_stamped_name = data_server_path + server_data_names_map[selected_data] + cur_time_stamp
            cur_data.to_csv(new_stamped_name + ".csv", index=False)
            request.session['passed_data_name'] = new_stamped_name
        return HttpResponseRedirect(reverse('syntheticbox:proc_data_dash'))
    else:
        return render(request, "syntheticbox/index.html", context)


def proc_data_dash(request):
    passed_data_name = request.session.get('passed_data_name')
    passed_data_name2 = request.session.get('passed_data_name2')
    passed_join_column = request.session.get('passed_join_column')
    passed_join_type = request.session.get('passed_join_type')

    json_cate_info = wrapper.get_dataset_info(passed_data_name + ".csv")
    att_list = json_cate_info["attribute_list"]
    cat_att_list = json_cate_info["categorical_attributes"]
    key_att_list = json_cate_info['candidate_attributes']
    json_data_table = []
    json_header_table = []
    for i in range(len(att_list)):
        json_data_table.append({"data": str(att_list[i])})
        json_header_table.append({"title": str(att_list[i]), "targets": i})
    json_cate_info2 = wrapper.get_dataset_info(passed_data_name2 + ".csv")
    att_list2 = json_cate_info2["attribute_list"]
    cat_att_list2 = json_cate_info2["categorical_attributes"]
    key_att_list2 = json_cate_info2['candidate_attributes']
    for k in range(len(att_list2)):
        #if (str(att_list2[k]) == passed_join_column):
        #    continue
        json_data_table.append({"data": str(att_list2[k])})
        json_header_table.append({"title": str(att_list2[k]), "targets": i + k + 1})
    # request information    
    request.session['passed_json_columns'] = json_data_table
    request.session['passed_column_name'] = att_list
    data_type_list = []
    for i in att_list:
        data_type_list.append(json_cate_info["attribute_datatypes"][i])

    tuple_n = json_cate_info["number_of_tuples"]
    passed_data_size = getSizeOfDataset(passed_data_name)
    context = {"passed_data_name": passed_data_name, 
               "passed_data_name2": passed_data_name2, 
               "passed_json_columns": json_data_table,
               "passed_column_name": att_list, 
               "passed_json_columns_header": json_header_table,
               "passed_cat_atts": cat_att_list, 
               "passed_att_types": data_type_list, 
               "tuple_n": tuple_n,
               "passed_key_atts": key_att_list, 
               "passed_data_size": passed_data_size,
               "passed_join_column": passed_join_column,
               "passed_join_type": passed_join_type}
    return render(request, "syntheticbox/proc_data_dash.html", context)


def proc_json_processing(request):
    passed_data_name = request.session.get('passed_data_name')
    passed_data_name2 = request.session.get('passed_data_name2')
    passed_join_column = request.session.get('passed_join_column')
    passed_join_type = request.session.get('passed_join_type')
    up_data = DataAnalyzerUI()
    up_data.read_dataset_from_csv(passed_data_name, passed_data_name2, passed_join_column, passed_join_type)
    up_data.get_json_data()
    total_json = up_data.json_data
    return HttpResponse(total_json, content_type='application/json')


def res_json_processing(request):
    passed_data_name = request.session.get('passed_data_name')
    up_data = DataAnalyzerUI()
    up_data.read_dataset_from_csv(passed_data_name)
    up_data.get_json_data()
    total_json = up_data.json_data
    return HttpResponse(total_json, content_type='application/json')


def res_json_processing_after(request):
    passed_data_name = request.session.get('passed_data_name')
    up_data = DataAnalyzerUI()
    up_data.read_dataset_from_csv('{}_synthetic_data'.format(passed_data_name))
    up_data.get_json_data()
    total_json = up_data.json_data
    return HttpResponse(total_json, content_type='application/json')


def res_json_processing_plot(request):
    passed_data_name = request.session.get('passed_data_name')
    passed_slicer_field = request.session.get('passed_slicer_field')
    passed_slicer_value = request.session.get('passed_slicer_value')
    print("plot processing: "+str(passed_slicer_field)+":"+str(passed_slicer_value))       
    description_file = passed_data_name + "_plot.json"
    if passed_slicer_field and passed_slicer_field != '':
        synthetic_data_name = passed_data_name + "_synthetic_data.csv"                
        wrapper.get_plot_data(passed_data_name + ".csv", 
                              synthetic_data_name, 
                              description_file, 
                              slicer=passed_slicer_field,
                              value=passed_slicer_value)
    plot_json = wrapper.read_metadata(description_file)
    return HttpResponse(json.dumps(plot_json), content_type='application/json')
    
    

synthetic_template/webUI/templates/syntheticbox/index.html
{% load static %}

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Syndata">
    <meta name="author" content="Syndata AB">

    <title>Syndata</title>
    <meta name="description" content="Syndata solves real data problems without the real data risks">
    <!-- CSS -->
    <link href="{% static 'bootstrap/css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'others/css/fileinput.min.css' %}" rel="stylesheet">
    <link href="{% static 'others/css/landing-page.css' %}" rel="stylesheet">
    <!-- bootstrap-select -->
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.6.3/css/bootstrap-select.min.css" />
    <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet"
          type="text/css">
    <script src="{% static 'jquery/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</head>

<body>

<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="navbar-header">
                    <!--<div class="navbar-brand navbar-left">
                        <img id="dt_logo" style="margin-top: 0px;margin-left: 350px;width: 50%" class="img-responsive" src="{% static 'images/rsz_header_logo.png' %}">
                    </div>-->
                    <div class="navbar-brand">
                        <img style="margin-top: 100px;margin-left:50px;width: 100%" class="img-responsive" src="{% static 'images/rsz_datasynthesizer_logo.png' %}">
                    </div>
                    <div class="intro-message">
                        <div class="col-lg-6">
                        <form method="post" onsubmit="return validateInput()" enctype="multipart/form-data">{% csrf_token %}
                            <h4>Load a real dataset in a CSV file</h4>
                            <input id="file_upload" size="50%" type="file" accept=".csv" class="filestyle" data-icon="false" name="user_upload_data" onchange='triggerValidation(this)'>
                            <input id="file_upload2" size="50%" type="file" accept=".csv" class="filestyle" data-icon="false" name="user_upload_data2" onchange='triggerValidation(this)'>
                            <h3>Join on </h3>
                            <input id="join_column" size="50%" type="text" class="" name="user_join_column" value="customerid">
                            <select id="join_type" name="user_join_type">
                                <option value="left">Left</option>
                                <option value="right">Right</option>
                                <option value="inner">Inner</option>
                                <option value="outer">Outer</option>
                            </select>
                            
                            <!--<h4>Select a sample dataset<span>&nbsp;&nbsp;</span></h4>
                            <select id="dataset_select" name="dataset_select" class="selectpicker">
                                {% for datai in passed_play_data %}
                                 <option value="{{ datai | safe }}">{{ datai }}</option>
                                {% endfor %}
                            </select>-->
                            <!--<span><br><br></span>-->
                            <input id="upload_btn" class="btn btn-default btn-lg top-buffer" aria-haspopup="true"
                                   aria-expanded="false" type="submit" value="Upload Data"/>
                        </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- FOOTER -->
<div class="footer_div">
    <div class="container_footer">
        <footer class="main_footer">
            <p class="text-muted">
                &copy; 2020 <a href="https://syndata.co"> Syndata</a>
                | <a href="https://syndata.co/privacy">Privacy</a>
                | <a href="https://syndata.co">Contact Us</a>
            </p>
        </footer>
    </div>
</div>

<style>

    .main_footer {
        background: inherit;
    }

    .container_footer {
        display: flex;
        justify-content: center;
    }

</style>

<!-- play data toolip setting-->
<script type="text/javascript" language="javascript">
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip({
        title: "All the test datasets here are sample datasets. The original datasets can be found in our GitHub repository. Check the code link in the footer of this page!",
        });
});
</script>
<!-- if upload data size less than threshold, then alert user to upload new data or leave it blank use test data-->
<script type="text/javascript" language="JavaScript">
    function validateInput() {
        if (!$("input[id='file_upload']").val()) {
            alert('Please upload a .csv file');
            return false;
        }
        return true;   
    }

    // validate upload data size
    //var data_size_flag = {{passed_size_flag | safe}};
    //if (data_size_flag == false){
    //    alert("You need to upload a data set that has more than 20 rows! Or leave it blank to use our test data!");
    //}
</script>
<!-- if upload data is not .csv file, then alert user to upload new data or leave it blank to use test data-->
<script type="text/javascript" language="javascript">
    // for browser that does not support .csv accept
    var regex = new RegExp("(.*?)\.(csv)$");

    function triggerValidation(el) {
      if (!(regex.test(el.value.toLowerCase()))) {
        el.value = '';
        alert('Please upload a .csv file with more than 20 rows');
      }
    }

</script>



<!-- JavaScript -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static 'others/js/bootstrap-filestyle.min.js' %}"></script>
<script src="{% static 'others/js/fileinput.min.js' %}"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.6.3/js/bootstrap-select.min.js"></script>
</body>
</html>

synthetic_template/webUI/templates/syntheticbox/proc_data_dash.html
{% load static %}
<head>
    <!-- Bootstrap Core CSS -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">    
    <!-- MetisMenu CSS -->
    <link href="{% static 'metisMenu/metisMenu.min.css' %}" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="{% static 'sbadmin/css/sb-admin-2-original.css' %}" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="{% static 'others/css/fileinput.min.css' %}" rel="stylesheet">
    <link href="{% static 'others/css/landing-page.css' %}" rel="stylesheet">        
    <!-- Custom Fonts -->
    <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">   
    <!-- jQuery -->
    <script src="{% static 'jquery/jquery-3.2.1.min.js' %}"></script>
    <!-- Bootstrap-select -->
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.6.3/css/bootstrap-select.min.css" />
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet"
          type="text/css">
    <link href="{% static 'datatables/media/css/jquery.dataTables.css' %}" rel="stylesheet">
    <link href="{% static 'others/css/landing-page.css' %}" rel="stylesheet">
    <script src="{% static 'datatables/media/js/jquery.dataTables.js' %}"></script>
    <!-- Highcharts JavaScript -->
    <script src="{% static 'highcharts/code/highcharts.js' %}"></script>
    <script src="{% static 'highcharts/code/modules/exporting.js' %}"></script>
</head>

<body>
<!-- HEADER/LOGO -->
<div class="intro-header">
    <div class="navbar-brand">
        <img style="margin-top: 0px;margin-left:10px;width: 100%" class="img-responsive" src="{% static 'images/rsz_datasynthesizer_logo.png' %}">
    </div>
</div>
<!-- PREVIEW PANEL -->
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-success">
            <div class="panel-heading">
                <h4 class="panel-title"> Preview (showing first 100 rows)​ </h4>
            </div>
            <div class="panel-body">
                <table id="proc_data_table" class="display nowrap" cellspacing="0" width="100%"> </table>
            </div>
        </div>
    </div>
</div>
<!-- /.row -->
<div class="row">
    <div class="col-lg-12">
    </div> <!-- /#col-12 -->
</div> <!-- /#row -->
<!-- FOOTER -->
<div class="footer_div">
    <div class="container_footer">
        <footer class="main_footer">
            <p class="text-muted">
                &copy; 2020 <a href="https://syndata.co"> Syndata</a>
                | <a href="https://syndata.co/privacy">Privacy</a>
                | <a href="https://syndata.co">Contact Us</a>
            </p>
        </footer>
    </div>
</div>
<style>
    .main_footer {
        background: inherit;
    }
    .container_footer {
        display: flex;
        justify-content: center;
    }
</style>

<script type="text/javascript" language="javascript">

    $(document).ready(function () {
        $('#proc_data_table').dataTable({
            "ajax": {
                "url": "{% url 'syntheticbox:proc_json_processing' %}",
                "dataSrc": ""
            },
            columns: {{passed_json_columns | safe}},
            columnDefs: {{passed_json_columns_header | safe}},
            order: [[ 0, "desc" ]],
            scrollX: true,
        });
    });

</script>

<!-- JavaScript -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static 'others/js/bootstrap-filestyle.min.js' %}"></script>
<script src="{% static 'others/js/fileinput.min.js' %}"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.6.3/js/bootstrap-select.min.js"></script>
<!-- Bootstrap Core JavaScript -->
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</body>
</html>