synthetic_template/webUI/syndataUI/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.base, name='base'),
    url(r'^syntheticbox/', include('syntheticbox.urls')),
    url(r'^admin/', admin.site.urls),

]
if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

synthetic_template/webUI/syntheticbox/urls.py
from django.conf.urls import url

from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns 

app_name = 'syntheticbox'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^proc_data_dash/$', views.proc_data_dash, name='proc_data_dash'),
    url(r'^proc_json_processing/$', views.proc_json_processing, name='proc_json_processing'),
    url(r'^res_json_processing_plot/$', views.res_json_processing_plot, name='res_json_processing_plot'),
    url(r'^res_json_processing/$', views.res_json_processing, name='res_json_processing'),
    url(r'^res_json_processing_after/$', views.res_json_processing_after, name='res_json_processing_after'),
]

urlpatterns += staticfiles_urlpatterns()

synthetic_template/webUI/templates/base.html
{% load static %}

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Syndata">
    <meta name="author" content="Drexel database group">

    <title>Syndata</title>
    <meta name="description" content="Syndata solves real data problems without the real data risks">
    <link rel="shortcut icon" type="image/png" href="{% static 'icons/rankingfacts.ico' %}" />
    <!-- CSS -->
    <link href="{% static 'bootstrap/css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'others/css/fileinput.min.css' %}" rel="stylesheet">
    <link href="{% static 'others/css/landing-page.css' %}" rel="stylesheet">
    <!-- bootstrap-select -->
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.6.3/css/bootstrap-select.min.css" />
    <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet"
          type="text/css">
    <script src="{% static 'jquery/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</head>

<body>

<div class="intro-header">
    <div class="container">

        <div class="row">
            <div class="col-lg-12">
                <div class="navbar-header">
                    <!--<div class="navbar-brand navbar-left">-->
                        <!--&lt;!&ndash;<img id="dt_logo" class="img-responsive" src="{% static 'images/TranspaRank_Logo.png' %}">&ndash;&gt;-->
                    <!--</div>-->
                    <div class="navbar-brand navbar-right">
                        <img id="head_logo" class="img-responsive" src="{% static 'images/header_logo.png' %}">
                    </div>
                    <div class="intro-message">
                        <h1>Ranking Facts</h1>
                        <hr class="intro-divider">
                        <form method="post" enctype="multipart/form-data">{% csrf_token %}
                            <h2>Upload a real dataset</h2>
                            <input id="file_upload" type="file" accept=".csv" class="filestyle" data-icon="false" name="user_upload_data" onchange='triggerValidation(this)' />
                            <br>
                            <!--<h2>OR</h2>
                            <br>
                            <h2>Play with our test data <span>&nbsp;&nbsp;</span> <a style="color: #0f0f0f" data-toggle="tooltip" data-placement="right"><i class="fa fa-question-circle fa-1x"></i></a></h2>
                            <select id="dataset_select" name="dataset_select" class="selectpicker">
                                {% for datai in passed_play_data %}
                                 <option value="{{ datai | safe }}">{{ datai }}</option>
                                {% endfor %}
                            </select>-->


                            <span><br><br><br><br></span>
                            <input id="upload_btn" class="btn btn-default btn-lg top-buffer" aria-haspopup="true"
                                   aria-expanded="false" type="submit" value="Upload Data"/>
                        </form>
                        <input id="size_tag" type="text" style="display:none;"/>
                    </div>
                </div>
            </div>
        </div>

    </div>

</div>

<!-- FOOTER -->
<div class="footer_div">
    <div class="container_footer">
        <footer class="main_footer">
            <p class="text-muted">
                &copy; 2017 <a href="https://syndata.co">Syndata</a>
                | <a href="https://syndata.co/privacy">Privacy</a>
                | <a href="https://syndata.co">Contact Us</a>
            </p>
        </footer>
    </div>
</div>

<style>

    .main_footer {
        background: inherit;
    }
    .container_footer {
        display: flex;
        justify-content: center;
    }
</style>
<!-- play data toolip setting
<script type="text/javascript" language="javascript">
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip({
        title: "All the test datasets here are sample datasets. The original datasets can be found in our GitHub repository. Check the code link in the footer of this page!",
        });
});-->
</script>
<!-- if upload data size less than threshold, then alert user to upload new data or leave it blank use test data-->
<script type="text/javascript" language="JavaScript">
    // validate upload data size
    var data_size_flag = {{passed_size_flag | safe}};
    if (data_size_flag == false){
        alert("You need to upload a data set that has more than 20 rows! Or leave it blank to use our test data!");
    }
</script>
<!-- if upload data is not .csv file, then alert user to upload new data or leave it blank to use test data-->
<script type="text/javascript" language="javascript">
    // for browser that does not support .csv accept
    var regex = new RegExp("(.*?)\.(csv)$");

    function triggerValidation(el) {
      if (!(regex.test(el.value.toLowerCase()))) {
        el.value = '';
        alert('Please upload a .csv file!');
      }
    }

</script>

<!-- JavaScript -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static 'others/js/bootstrap-filestyle.min.js' %}"></script>
<script src="{% static 'others/js/fileinput.min.js' %}"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.6.3/js/bootstrap-select.min.js"></script>

</body>
</html>

synthetic_template/webUI/templates/tools.html
{% load static %}

<html class="no-js">
  <head>
  	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Tools</title>
	<meta name="description" content="">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- CSS -->
	<link rel="stylesheet" href="{% static 'jekyll/css/owl.carousel.css' %}" />
	<link rel="stylesheet" href="{% static 'jekyll/css/bootstrap.min.css' %}" />
	<link rel="stylesheet" href="{% static 'jekyll/css/font-awesome.min.css' %}" />
	<link rel="stylesheet" href="{% static 'jekyll/css/themes.css' %}" />
	<link rel="stylesheet" href="{% static 'jekyll/css/style.css' %}" />
	<link rel="stylesheet" href="{% static 'jekyll/css/ionicons.min.css' %}" />
	<link rel="stylesheet" href="{% static 'jekyll/css/animate.css' %}" />
	<link rel="stylesheet" href="{% static 'jekyll/css/responsive.css' %}" />
	<link rel="stylesheet" href="{% static 'jekyll/css/syntax.css' %}" />

	<!-- Js -->
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
	<!--<script>window.jQuery || document.write('<script src="js/vendor/jquery-1.10.2.min.js"><\/script>')</script>-->

	<script src="{% static 'jekyll/js/vendor/jquery-1.10.2.min.js' %}"></script>
    <script src="{% static 'jekyll/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'jekyll/js/owl.carousel.min.js' %}"></script>
	<script src="{% static 'jekyll/js/plugins.js' %}"></script>
	<script src="{% static 'jekyll/js/min/waypoints.min.js' %}"></script>
	<script src="{% static 'jekyll/js/jquery.counterup.js' %}"></script>


	<script src="{% static 'jekyll/js/main.js' %}"></script>
  </head>
  <body>

  	<!-- Header Start -->
	<header>
	<div class="container">
	  <div class="row">
	    <div class="col-md-12">
	      <!-- header Nav Start -->
	      <nav class="navbar navbar-default">
	        <div class="container-fluid">
	          <!-- Brand and toggle get grouped for better mobile display -->
	          <div class="navbar-header">
	            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
	            <span class="sr-only">Toggle navigation</span>
	            <!-- <span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
	            <span class="icon-bar"></span> -->
	            </button>
				<a class="navbar-brand" href="https://syndata.co">
					<img style="margin-top: 0px;margin-left: 0px;width: 100%;" src="{% static 'images/header_logo.png' %}" alt="Logo">
	            </a>
	          </div>
	            <!-- Collect the nav links, forms, and other content for toggling -->
	            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	              <ul class="nav navbar-nav navbar-right">
	                <li><a href="https://syndata.co">Home</a></li>
	                <li><a href="https://syndata.co/privacy">Privacy</a></li>
	                <li><a href="{% url 'syntheticbox:index' %}">Synthetic Engine</a></li>
	                <li><a href="https://syndata.co">Contact</a></li>
	              </ul>
	            </div><!-- /.navbar-collapse -->
	          </div><!-- /.container-fluid -->
	          <div><p></p></div>
	        </nav>
	      </div>
	    </div>
	  </div>
	</header><!-- header close -->

	<!-- Slider Start -->
	<!-- <section id="global-header">
	  <div class="container">
	    <div class="row">
	      <div class="col-md-12">
	        <div class="block">
	          <h1>Tools</h1>
	          <p>all our code is open-source</p>
	        </div>
	      </div>
	    </div>
	  </div>
	</section>-->
	<section id="portfolio-work">
	    <div class="container">
	        <div class="row">
	          <div class="col-lg-16">
	            <div class="block">
	              <div class="portfolio-contant">
	                <ul id="portfolio-contant-active-tools">
	                    <li>
						  <!--<a href="{% url 'syntheticbox:index' %}"></a>
	                        <img style ="width: 120%;height: 25%" src="{% static 'images/DataSynthesizer_Logo_Small.png' %}" alt="TheSyntheticBox">
	                        <div class="overly">
	                            <h2>The Synthetic Box</h2>
	                            <p>Generate synthetic datasets</p>
	                        </div>
	                      </a>-->
	                    </li>
	                </ul>
	              </div>
	            </div>
	          </div>
	        </div>
	    </div>
	</section>

    <!-- footer Start -->
	<footer>
	  <div class="container">
	    <div class="row">
	      <div class="col-md-12">
	        <div class="footer-manu">
	          <ul>
	            <li><a href="https://syndata.co">About Us</a></li>
	            <li><a href="https://syndata.co">Contact us</a></li>
	          </ul>
	        </div>
	        <!--<p>Copyright &copy; Design &amp; Referenced the theme <a href="http://www.themefisher.com">Themefisher</a>. All rights reserved.</p>-->
	      </div>
	    </div>
	  </div>
	</footer>

    </body>
</html>